# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xms512M
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.caching.debug=false
org.gradle.configureondemand=true

# Mod properties
mod.version=0.2.4
mod.group=me.enderkill98
mod.id=proxlib
mod.name=ProxLib
mod.loader=neoforge

# for neoforge.mods.toml
mod.mc_dep=VERSIONED

# Versioned dependencies
deps.neo_version=VERSIONED
deps.parchment_mappings=VERSIONED

# Publishing
#publish.modrinth=...
#publish.curseforge=...